---
title: "Bioenergy cropland expansion may offset positive effects of climate change mitigation for global vertebrate diversity"
author: "Christian Hof, Alke Voskamp, Matthias F. Biber, Katrin Böhning-Gaese, Eva-Katharina Engelhardt, Aidin Niamir, Stephen G. Willis Thomas Hickler"
output: github_document
---

# Abstract

Climate and land-use change interactively affect biodiversity. Large-scale
expansions of bioenergy have been suggested as an important component for climate change mitigation. Here we use harmonized climate and land-use projections to investigate their potential combined impacts on global vertebrate diversity under a low- and a high-level emission scenario. We combine climate-based species distribution models for the world's amphibians, birds, and mammals with land-use change simulations and identify areas threatened by both climate and land-use change in the future. The combined projected effects of climate and land-use change on vertebrate diversity are similar under the two scenarios, with land-use change effects being stronger under the low-level and climate change effects under the
high-emission scenario. Under the low-emission scenario, increases in bioenergy croplandmay cause severe declines in biodiversity that are not compensated by lower climate change impacts. Under this lowemission scenario, larger proportions of species distributions and a higher number of small-range species may become impacted by the combination of land-use and climate change than under the highemission
scenario, largely a result of bioenergy cropland expansion. Our findings highlight the need to carefully consider both climate and land-use change when projecting biodiversity impacts. We show that biodiversity is likely to suffer severely if bioenergy cropland expansion remains a major component of climate change mitigation
strategies. Our study calls for an immediate and significant reduction in energy consumption for the benefit of both biodiversity and to achieve the goals of the Paris Agreement.
